/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (ColinMcRaeRally)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800EC4D4u
#define func_800EC4D4 BootEntry  /* alias */
